### ISSUE TITLE
Reachability dsym in archive

### ISSUE THREAD

**Issue by Mortenest** [nodes-ios/Blobfish#9]
I am using Carthage for installing Blobfish,
but when archiving the app, it is not possible to upload it to app store, due to Reachability.dSYM that is in the archive under:
~/Library/Developer/Xcode/Archives/2016-04-14/ARCHIVENAME.xcarchive/Products/Applications/APPNAME.app/Frameworks/Blobfish.framework

This means that I have to manually delete that dsym every time I have to upload.

I am not sure where the error lies though (Reachability or Blobfish).

Any thoughts?

**Comment by kasperwelner** [comment]
It should be fixed in the newest release from yesterday! 

## 

Kasper Welner
iOS Lead

Nodes - We build awesome digital stuff

Mobile:  +45 41 62 60 20
Web:   http://www.nodes.dk http://www.nodes.dk/

**Comment by Mortenest** [comment]
fedt mand!
